#This document tells us what do we want
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: mongo-vpc
spec:
  resources:
    requests:
      storage: 10Gi

---
#This document tells us how do we implement
apiVersion: v1 
kind: PersistentVolume
metadata:
  name: local-storage-demo
spec:
  hostPath:
    path: "/mnt/somedir/dir01/folder01/"

  